### ISSUE TITLE
Error Instalation

### ISSUE THREAD

**Issue by ghost** [jagi/meteor-astronomy-examples#3]
```
W20150915-16:31:03.427(7)? (STDERR) /Users/user/.meteor/packages/meteor-tool/.1.1.3.dzw9kd++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20150915-16:31:03.427(7)? (STDERR)                         throw(ex);
W20150915-16:31:03.427(7)? (STDERR)                               ^
W20150915-16:31:03.484(7)? (STDERR) TypeError: Object #<Object> has no method 'findInClass'
W20150915-16:31:03.484(7)? (STDERR)     at Object.Astro.utils.findBehavior (packages/jagi:astronomy-behaviors/lib/module/utils.js:2:1)
W20150915-16:31:03.484(7)? (STDERR)     at Function.checks.added (packages/jagi:astronomy-behaviors/lib/module/init_class.js:31:1)
W20150915-16:31:03.484(7)? (STDERR)     at Function.methods.addBehavior (packages/jagi:astronomy-behaviors/lib/module/init_class.js:69:1)
W20150915-16:31:03.484(7)? (STDERR)     at Function.<anonymous> (packages/jagi:astronomy-behaviors/lib/module/init_class.js:87:1)
W20150915-16:31:03.484(7)? (STDERR)     at Array.forEach (native)
W20150915-16:31:03.485(7)? (STDERR)     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
W20150915-16:31:03.485(7)? (STDERR)     at Function.methods.addBehaviors (packages/jagi:astronomy-behaviors/lib/module/init_class.js:86:1)
W20150915-16:31:03.485(7)? (STDERR)     at Function.onInitClass (packages/jagi:astronomy-behaviors/lib/module/init_class.js:117:1)
W20150915-16:31:03.485(7)? (STDERR)     at packages/jagi:astronomy/lib/core/class.js:81:1
W20150915-16:31:03.485(7)? (STDERR)     at packages/jagi:astronomy/lib/core/events.js:55:1
```

**Comment by ghost** [comment]
Run after update the packages
